name: Matlab CIEDE2000 Testing

# During summer 2025, this workflow was tested on several weekends and completed successfully in 150 seconds.

on:
  schedule:
    - cron: '16 4 10 * *'
  workflow_dispatch:

env:
  description: "Automated Testing â€” Michel Leonard implements the CIE2000 color difference formula in Matlab"
  input_file: "test-cases.csv contains lines like 70.8,31,-11.3,88,49,5 representing two L*a*b* colors"
  process:  "Print the line with its Delta E like 70.8,31,-11.3,88,49,5,16.393124795959094672443221339537 for each line"
  related_url: "https://github.com/michel-leonard/ciede2000-color-matching/tree/main/tests/m"
  n_csv_lines: 10000000

jobs:
  test-implementation-de00-m:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: ğŸ“‚ For each step below, a new shell will be started at the repository root
        uses: actions/checkout@v6

      - name: ğŸ‘‰ Disable the user manual database, which is not needed in this CI/CD workflow
        run: sudo ln --backup --symbolic --verbose $(which true) $(which mandb)

      - name: ğŸ‘‰ Set up a less crowded server for the APT package manager (step disabled, but useful when an installation is slow)
        run: true || grep -Flr '.ubuntu.com' /etc/apt | xargs sudo sed -i 's|[^/]\+ubuntu.com|mirrors.maine.edu|g'

      - name: ğŸ“¦ Set up GNU Octave and GCC
        run: |
          command -v octave > /dev/null || { sudo apt-get update --allow-unauthenticated && sudo apt-get install --allow-unauthenticated --no-install-recommends --assume-yes octave ; }
          command -v gcc > /dev/null || { sudo apt-get update --allow-unauthenticated && sudo apt-get install --allow-unauthenticated --no-install-recommends --assume-yes gcc ; }

      - name: ğŸ”§ Prepare the Matlab testing file
        run: cp -p tests/m/ciede-2000-driver.m main.m

      - name: âš™ï¸ Compile the CIEDE2000 driver program in C99
        run: gcc --version && gcc -std=c99 -Wall -pedantic -O2 -g tests/c/ciede-2000-driver.c -o ciede-2000-driver -lm

      - name: ğŸ“‘ Display help for the authoritative test software
        run: ./ciede-2000-driver --help

      - name: ğŸ¨ Generate Î”E2000 color difference test cases
        run: |
          # Splits the large file into as many smaller files as there are vCPUs
          n_cpu=$(nproc) && ./ciede-2000-driver --rand-seed $(date +'%Y%V') --generate $n_csv_lines |
          split --unbuffered --lines=$(( ($n_csv_lines + $n_cpu - 1) / $n_cpu )) --numeric-suffixes=1 --additional-suffix=.csv - test-cases-
          # Shows the name, size and first line of newly created files
          du -h test-cases-* | awk '{getline line < $2; print $2, "(" $1 "B) contains L*a*b* color pairs for vCPU " NR ", first values =", line}'

      - name: âš¡ Solves test cases by calculating Î”E2000 in Matlab (parallelized operation)
        run: |
          for file in test-cases-*; do
            OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1 octave --quiet --eval "main(\"$file\")" > solved-$file &
            echo "Processes $file ($(wc -l < $file) lines) in parallel â¤ solved-$file"
          done
          wait

      - name: ğŸš€ Check that C99 calculations matches Matlabâ€™s
        run:  cat solved-* | ./ciede-2000-driver -o summary.txt

      - name: ğŸ” Display verification output
        run: cat summary.txt

      - name: ğŸ Conclusion
        run: |
          if grep -q "Errors : 0" summary.txt && grep -q "Successes : $n_csv_lines" summary.txt; then
            echo "âœ”ï¸ Verification successful: all $n_csv_lines color differences were correctly calculated."
          else
            echo "âŒ Verification failed. See above for details."
            exit 1
          fi
