name: C++ CIEDE2000 Testing

# During summer 2025, this workflow was tested on several weekends and completed successfully in 34 seconds.

on:
  schedule:
    - cron: '18 4 18 * *'
  workflow_dispatch:

env:
  description: "Automated Testing â€” Michel Leonard implements the CIE2000 color difference formula in C++"
  input_file: "test-cases.csv contains lines like 5,-26.9,101,14.6,18,80 representing two L*a*b* colors"
  process:  "Print the line with its Delta E like 5,-26.9,101,14.6,18,80,24.684326111430396277463010129231 for each line"
  related_url: "https://github.com/michel-leonard/ciede2000-color-matching/tree/main/tests/cpp"
  n_csv_lines: 10000000

jobs:
  test-implementation-de00-cpp:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: ğŸ“‚ For each step below, a new shell will be started at the repository root
        uses: actions/checkout@v6

      - name: ğŸ‘‰ Disable the user manual database, which is not needed in this CI/CD workflow
        run: sudo ln --backup --symbolic --verbose $(which true) $(which mandb)

      - name: ğŸ‘‰ Set up a less crowded server for the APT package manager (step disabled, but useful when an installation is slow)
        run: true || grep -Flr '.ubuntu.com' /etc/apt | xargs sudo sed -i 's|[^/]\+ubuntu.com|mirrors.maine.edu|g'

      - name: ğŸ“¦ Set up g++ and GCC
        run: |
          command -v g++ > /dev/null || { sudo apt-get update --allow-unauthenticated && sudo apt-get install --allow-unauthenticated --no-install-recommends --assume-yes g++ ; }
          command -v gcc > /dev/null || { sudo apt-get update --allow-unauthenticated && sudo apt-get install --allow-unauthenticated --no-install-recommends --assume-yes gcc ; }

      - name: âš™ï¸ Compile the CIEDE2000 test program in C++
        run: g++ --version && g++ -std=c++14 -Wall -Wextra -Wpedantic -Ofast -o driver-cpp tests/cpp/ciede-2000-driver.cpp

      - name: âš™ï¸ Compile the CIEDE2000 driver program in C99
        run: gcc --version && gcc -std=c99 -Wall -pedantic -O2 -g tests/c/ciede-2000-driver.c -o ciede-2000-driver -lm

      - name: ğŸ“‘ Display help for the authoritative test software
        run: ./ciede-2000-driver --help

      - name: ğŸ¨ Generate Î”E2000 color difference test cases
        run: ./ciede-2000-driver --rand-seed $(date +'%Y%V') --generate $n_csv_lines --output-file test-cases.csv

      - name: ğŸš€ Run test cases in C++ and stream to verifier
        run: ./driver-cpp test-cases.csv | ./ciede-2000-driver -o summary.txt

      - name: ğŸ” Display verification output
        run: cat summary.txt

      - name: ğŸ Conclusion
        run: |
          if grep -q "Errors : 0" summary.txt && grep -q "Successes : $n_csv_lines" summary.txt; then
            echo "âœ”ï¸ Verification successful: all $n_csv_lines color differences were correctly calculated."
          else
            echo "âŒ Verification failed. See above for details."
            exit 1
          fi
